version: "3.9"

services:

  postgres:

    image: postgres:17

    container_name: money_solver_postgres

    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: money_solver

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data: